# Generated by Django 4.0.4 on 2024-06-20 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('qr_code', models.ImageField(blank=True, upload_to='Attendance')),
            ],
            options={
                'verbose_name_plural': 'Attendance QR',
            },
        ),
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Drs',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('qr_code', models.ImageField(blank=True, upload_to='leave')),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dr')),
            ],
            options={
                'verbose_name_plural': 'Leave QR',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Leave_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(blank=True, max_length=100)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dr')),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.leave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leave List',
            },
        ),
        migrations.CreateModel(
            name='Attendance_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(blank=True, max_length=100)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dr')),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.attendance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendance List',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='dr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dr'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject'),
        ),
    ]
