# Generated by Django 4.0.4 on 2024-08-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_attendance_responsibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='dr',
        ),
    ]
